apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: puzle/myrepository:latest
    ports:
    - containerPort: 8000  # Порт внутри контейнера
      #hostPort: 8000     # Порт на хосте, который будет проброшен (эта строка чот не сработала)
